"""
HEIST GRPO Training Script — Step 11.

Why GRPO?
---------
PPO requires a value function (critic) that is unstable on sparse 50-step episodes
where reward only arrives when the SAR is finally filed. DPO needs curated
preference pairs which do not exist for novel adversarial schemes generated by the
Criminal Codex at runtime. GRPO operates from the reward signal alone: it samples
G rollouts per prompt, normalises them within the group, and updates the policy
without a critic — exactly what a sparse multi-step investigator reward demands.

Architecture
------------
Observation  →  prompt text  →  Qwen2.5-1.5B (4-bit, Unsloth)  →  action token
Action token →  HeistEnvironment.step()  →  next observation + reward
Episode done →  R_investigator computed  →  GRPO loss  →  gradient update

Files written
-------------
checkpoints/ckpt_ep{N}/     — model + tokenizer every 10 episodes
training_curves.json        — reward curve (episode -> R_investigator)
training_log.csv            — per-episode per-scheme-type F1 (for Red Queen)
"""

from __future__ import annotations

import csv
import json
import os
import sys
import time
import warnings
from typing import Any, Dict, List, Optional, Tuple

# Suppress the "Both max_new_tokens and max_length set" flood from HuggingFace
# generate() — happens because Unsloth sets generation_config.max_length=32768
# but we always pass max_new_tokens=40. Clearing generation_config below also
# helps, but this catches any residual firings from internal Unsloth calls.
warnings.filterwarnings(
    "ignore",
    message=r".*Both `max_new_tokens`.*and `max_length`.*",
    category=UserWarning,
)
# Transformers 5.5+ renamed AttentionMaskConverter — Unsloth hasn't updated yet
warnings.filterwarnings(
    "ignore",
    message=r".*AttentionMaskConverter.*deprecated.*",
    category=FutureWarning,
)
warnings.filterwarnings(
    "ignore",
    message=r".*use_return_dict.*deprecated.*",
    category=FutureWarning,
)

import numpy as np

# ---------------------------------------------------------------------------
# Resolve project root so env/ and agents/ imports work from train/
# ---------------------------------------------------------------------------
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
_ENV  = os.path.join(_ROOT, "env")
for _p in [_ROOT, _ENV]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

# ---------------------------------------------------------------------------
# Lazy imports — heavy ML deps only needed on Colab/GPU machine
# ---------------------------------------------------------------------------
def _import_ml():
    """Import ML stack lazily so env-only tests don't fail without GPU."""
    try:
        from unsloth import FastLanguageModel
        import torch
        from transformers import AutoTokenizer
        return FastLanguageModel, torch, AutoTokenizer
    except ImportError as e:
        raise ImportError(
            f"Missing ML dependency: {e}\n"
            "Install with: pip install unsloth transformers torch"
        ) from e

# ---------------------------------------------------------------------------
# Env imports (always available)
# ---------------------------------------------------------------------------
from heist_env import HeistEnvironment
from models import InvestigatorAction, ActionType
from reward import r_investigator
from curriculum import RedQueenCurriculum

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

# Unsloth 2024.11+ suppresses logits by default; our grpo_loss() needs them.
os.environ.setdefault("UNSLOTH_RETURN_LOGITS", "1")

MODEL_NAME      = os.environ.get("HEIST_MODEL",      "unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit")
MAX_SEQ_LEN     = int(os.environ.get("MAX_SEQ_LEN",  "2048"))
NUM_EPISODES    = int(os.environ.get("NUM_EPISODES",  "50"))    # 50 minimum for co-evolution story
GRPO_G          = int(os.environ.get("GRPO_G",       "8"))      # 8 rollouts: better variance reduction
LR              = float(os.environ.get("LR",          "5e-6"))  # 2e-5 caused overshooting once rewards[-1] range widened to 1.0-5.0
CODEX_UPDATE_K  = int(os.environ.get("CODEX_K",      "5"))      # criminal.adapt() every K eps
CKPT_EVERY      = int(os.environ.get("CKPT_EVERY",   "10"))     # checkpoint interval
OUT_DIR         = os.environ.get("OUT_DIR",           os.path.join(_ROOT, "checkpoints"))
RESUME_FROM     = os.environ.get("RESUME_FROM",       "")        # path to checkpoint dir to resume from; empty = start fresh
START_EPISODE   = int(os.environ.get("START_EPISODE", "1"))      # episode number to start counting from (set to N+1 when resuming from ckpt_epN)
CURVES_PATH     = os.environ.get("CURVES_PATH",       os.path.join(_ROOT, "training_curves.json"))
LOG_CSV         = os.environ.get("LOG_CSV",           os.path.join(_ROOT, "training_log.csv"))

# Action vocabulary the model can emit
ACTION_VOCAB = [
    "query_transactions",
    "trace_network",
    "lookup_entity",
    "cross_reference_jurisdiction",
    "request_subpoena",
    "file_SAR",
]

_ACTION_MAP = {
    "query_transactions":           ActionType.QUERY_TRANSACTIONS,
    "trace_network":                ActionType.TRACE_NETWORK,
    "lookup_entity":                ActionType.LOOKUP_ENTITY,
    "cross_reference_jurisdiction": ActionType.CROSS_REFERENCE,
    "request_subpoena":             ActionType.REQUEST_SUBPOENA,
    "file_SAR":                     ActionType.FILE_SAR,
}

# ---------------------------------------------------------------------------
# Prompt / response formatting
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = (
    "You are an elite AML investigator. Analyze the observation and choose ONE action.\n"
    "Available actions: " + ", ".join(ACTION_VOCAB) + ".\n\n"
    "PHASE STRATEGY:\n"
    "  AlertTriage:    query_transactions on the flagged entity to confirm flows (need ≥2)\n"
    "  Investigation:  trace_network to follow the money trail (need ≥5 traces)\n"
    "  CrossReference: cross_reference_jurisdiction on offshore entities (need ≥3)\n"
    "  SARFiling:      file_SAR immediately on your top suspects — every extra step hurts score!\n\n"
    "EFFICIENCY RULE: In SARFiling phase, do NOT hesitate. File immediately.\n"
    "Fewer steps used = higher query efficiency score = better total reward.\n\n"
    "EXACT FORMAT:\n"
    "  ACTION:<action_name> ENTITY:<entity_id>\n"
    "  OR for SAR: ACTION:file_SAR ENTITIES:<e1>,<e2>,<e3>"
)


def obs_to_prompt(obs_dict: Dict[str, Any]) -> str:
    """Format a HeistObservation dict into a text prompt."""
    phase   = obs_dict.get("current_phase", "AlertTriage")
    budget  = obs_dict.get("budget_remaining", 50)
    beliefs = obs_dict.get("bayesian_beliefs", {})
    flagged = obs_dict.get("flagged_transaction") or {}
    morph   = obs_dict.get("morph_alert", {})

    # Top-5 suspicious entities (more context for SAR filing)
    top5 = sorted(beliefs.items(), key=lambda x: -x[1])[:5]
    belief_str = " | ".join(f"{e}={p:.2f}" for e, p in top5) or "none"

    flagged_str = (
        f"{flagged.get('source_entity','?')} -> {flagged.get('target_entity','?')}"
        f" ${flagged.get('amount', 0):.0f}"
        if flagged else "none"
    )

    morph_str = f"MORPH_ALERT invalidated={morph.get('invalidated_entities', [])}" if morph.get("morph_occurred") else ""

    # Budget urgency — critical signal for efficiency learning
    if budget <= 10:
        urgency = f"🚨 CRITICAL: Only {budget} budget left! FILE SAR NOW!\n"
    elif budget <= 20:
        urgency = f"⚠️ WARNING: {budget} budget left. File SAR soon to maximize efficiency.\n"
    elif phase == "SARFiling":
        urgency = "✅ SARFiling phase reached. FILE SAR IMMEDIATELY on top suspects.\n"
    else:
        urgency = ""

    return (
        f"[PHASE:{phase}] [BUDGET:{budget}]\n"
        f"{urgency}"
        f"FLAGGED: {flagged_str}\n"
        f"TOP_SUSPECTS: {belief_str}\n"
        f"{morph_str}\n"
        "CHOOSE ACTION:"
    )


def parse_action(text: str, beliefs: Dict[str, float]) -> Tuple[str, Dict[str, Any]]:
    """
    Parse model output into (action_type, params).
    Gracefully falls back to heuristic if parsing fails.
    """
    import re
    text = text.strip()

    # Try structured parse
    action_match = re.search(r"ACTION:(\w+)", text)
    entity_match = re.search(r"ENTITY:(\S+)", text)
    entities_match = re.search(r"ENTITIES:([\w,_\-]+)", text)

    if not action_match:
        # Fallback: first action keyword found in text
        for act in ACTION_VOCAB:
            if act in text:
                action_match_str = act
                break
        else:
            action_match_str = "query_transactions"
    else:
        action_match_str = action_match.group(1)

    # Normalise action name
    action_type = action_match_str.strip()
    if action_type not in ACTION_VOCAB:
        action_type = "query_transactions"

    # Entity
    if action_type == "file_SAR":
        if entities_match:
            entities = entities_match.group(1).split(",")
        else:
            entities = list(beliefs.keys())[:5]
        return action_type, {"evidence_chain": entities}
    else:
        if entity_match:
            entity = entity_match.group(1)
        elif beliefs:
            entity = max(beliefs, key=beliefs.get)
        else:
            entity = ""
        return action_type, {"entity_id": entity}


# ---------------------------------------------------------------------------
# Rollout: run one episode, return trajectory
# ---------------------------------------------------------------------------

def run_rollout(
    env: HeistEnvironment,
    model,
    tokenizer,
    seed: int,
    use_model: bool = True,
    verbose: bool = False,
    expert=None,
    episode_num: int = 0,
    temperature: float = 0.7,
    preferred_scheme_type: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Run one complete episode.

    preferred_scheme_type: if set, passed to env.reset() so the Red Queen
    curriculum drives which scheme the investigator faces this episode.

    Returns a dict with:
        prompts:     List[str]   — text prompt at each step
        completions: List[str]   — model output at each step
        rewards:     List[float] — step reward (0 except last = R_investigator)
        r_inv:       float       — final R_investigator score
        scheme_type: str
        f1_by_type:  Dict[str, float]
    """
    obs = env.reset(seed=seed, scheme_type=preferred_scheme_type)
    obs_dict = obs.model_dump()
    scheme_type = obs_dict.get("metadata", {}).get("scheme_type", "unknown")

    prompts:     List[str]   = []
    completions: List[str]   = []
    step_rewards: List[float] = []
    evidence_chain: List[str] = []
    subpoenaed: set = set()
    action_type_log: List[str] = []   # interpretability: track action distribution

    done = False
    steps = 0
    final_compliance = 0.0
    final_beliefs: Dict[str, float] = {}

    while not done and steps < 50:
        steps += 1
        prompt_text = obs_dict_to_full_prompt(obs_dict)
        beliefs = obs_dict.get("bayesian_beliefs", {})

        if use_model and model is not None:
            # Generate one action token sequence
            inputs = tokenizer(
                prompt_text, return_tensors="pt", truncation=True, max_length=MAX_SEQ_LEN
            )
            import torch
            device = next(model.parameters()).device
            inputs = {k: v.to(device) for k, v in inputs.items()}
            with torch.no_grad():
                outputs = model.generate(
                    **inputs,
                    max_new_tokens=40,
                    do_sample=True,
                    temperature=temperature,
                    pad_token_id=tokenizer.eos_token_id,
                )
            generated = tokenizer.decode(
                outputs[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True
            )
        else:
            # Heuristic fallback (for testing without GPU)
            generated = _heuristic_action_text(obs_dict)

        action_type_str, params = parse_action(generated, beliefs)

        # For SAR filing: submit only high-confidence entities (P > 0.5) to reduce
        # false positives that tank precision. Previously we submitted ALL queried
        # entities, which capped F1 at ~0.5 because precision was always diluted.
        # Fall back to top-5 by belief if no entity clears the threshold.
        if action_type_str == "file_SAR" and evidence_chain:
            high_conf = [e for e in evidence_chain if beliefs.get(e, 0.0) > 0.5]
            if high_conf:
                params["evidence_chain"] = high_conf
            else:
                top5 = sorted(evidence_chain, key=lambda e: beliefs.get(e, 0.0), reverse=True)[:5]
                params["evidence_chain"] = top5

        # Accumulate evidence
        entity = params.get("entity_id", "")
        if entity and entity not in evidence_chain:
            evidence_chain.append(entity)

        # Step
        action = InvestigatorAction(
            action_type=_ACTION_MAP.get(action_type_str, ActionType.QUERY_TRANSACTIONS),
            params=params,
        )
        obs = env.step(action)
        obs_dict = obs.model_dump()

        # Immediate step reward
        step_r = float(obs_dict.get("reward", 0.0))

        prompts.append(prompt_text)
        completions.append(generated)
        step_rewards.append(step_r)
        action_type_log.append(action_type_str)   # track for entropy

        done = bool(obs_dict.get("done", False))
        final_beliefs = obs_dict.get("bayesian_beliefs", {})

        # Compliance score from SAR
        tool_result = obs_dict.get("tool_result") or {}
        data = tool_result.get("data", {})
        if "compliance_score" in data:
            tool_compliance = float(data["compliance_score"])
            if expert is not None and evidence_chain:
                ev_dicts = [{"entity_id": e} for e in evidence_chain]
                risk_score = max(final_beliefs.values()) * 10.0 if final_beliefs else 5.0
                exp_score, _ = expert.evaluate_SAR(
                    evidence_chain=ev_dicts,
                    risk_score=risk_score,
                    narrative=completions[-1] if completions else "",
                    episode_number=episode_num,
                    query_count=steps,
                )
                # 60% F1-based tool compliance, 40% expert satisfaction (preference drift)
                final_compliance = 0.6 * tool_compliance + 0.4 * exp_score
            else:
                final_compliance = tool_compliance

        if verbose:
            print(f"  step={steps:2d} | {action_type_str:30s} | R={step_r:+.2f} | budget={obs_dict.get('budget_remaining')}")

    gt = env._graph.ground_truth.get(env.state.scheme_id, {})
    true_path  = list(gt.get("full_path", []))
    scheme_t   = gt.get("scheme_type", scheme_type)

    r_inv_result = r_investigator(
        evidence_chain=evidence_chain,
        ground_truth_path=true_path,
        compliance_score=final_compliance,
        queries_used=steps,
        total_budget=50,
        query_history=env.state.query_history,
        graph=env._graph,
        scheme_type=scheme_t,
        is_codex_generated=False,
    )
    r_inv = float(r_inv_result["total"])

    # Assign terminal reward to last step only (sparse)
    if step_rewards:
        step_rewards[-1] += r_inv

    # Scheme-type F1 (for Red Queen curriculum CSV)
    predicted_set = set(evidence_chain)
    true_set = set(true_path)
    if true_set:
        tp = len(predicted_set & true_set)
        precision = tp / max(len(predicted_set), 1)
        recall    = tp / max(len(true_set), 1)
        f1 = 2 * precision * recall / max(precision + recall, 1e-9)
    else:
        f1 = 0.0

    # ── Interpretability metrics ───────────────────────────────────────
    # Action entropy: H = -Σ p(a) log p(a). Low entropy = more decisive.
    # Tracks whether the model is learning a coherent strategy or acting randomly.
    action_counts: Dict[str, int] = {}
    for a in action_type_log:
        action_counts[a] = action_counts.get(a, 0) + 1
    if action_counts:
        total_acts = len(action_type_log)
        import math as _math
        action_entropy = -sum(
            (c / total_acts) * _math.log(c / total_acts + 1e-9)
            for c in action_counts.values()
        )
    else:
        action_entropy = 0.0
    first_action = action_type_log[0] if action_type_log else "none"

    return {
        "prompts":        prompts,
        "completions":    completions,
        "rewards":        step_rewards,
        "r_inv":          r_inv,
        "scheme_type":    scheme_type,
        "f1":             f1,
        "f1_by_type":     {scheme_type: f1},
        "steps":          steps,
        "compliance":     final_compliance,
        "action_entropy": round(action_entropy, 4),
        "first_action":   first_action,
        "action_counts":  action_counts,
    }


def obs_dict_to_full_prompt(obs_dict: Dict[str, Any]) -> str:
    """Full prompt with system + observation."""
    return f"{SYSTEM_PROMPT}\n\n{obs_to_prompt(obs_dict)}"


def _heuristic_action_text(obs_dict: Dict[str, Any]) -> str:
    """Return a heuristic action in model output format (no GPU needed)."""
    phase   = obs_dict.get("current_phase", "AlertTriage")
    beliefs = obs_dict.get("bayesian_beliefs", {})
    flagged = obs_dict.get("flagged_transaction") or {}

    entity = (
        max(beliefs, key=beliefs.get)
        if beliefs
        else flagged.get("source_entity", "unknown")
    )

    phase_actions = {
        "AlertTriage":    "query_transactions",
        "Investigation":  "trace_network",
        "CrossReference": "cross_reference_jurisdiction",
        "SARFiling":      "file_SAR",
    }
    act = phase_actions.get(phase, "query_transactions")

    if act == "file_SAR":
        entities = ",".join(list(beliefs.keys())[:5])
        return f"ACTION:file_SAR ENTITIES:{entities}"
    return f"ACTION:{act} ENTITY:{entity}"


# ---------------------------------------------------------------------------
# Multi-step training helper
# ---------------------------------------------------------------------------

def _sample_key_steps(rollout: Dict, n_train: int = 5) -> List[int]:
    """
    Select n_train step indices per rollout for GRPO gradient updates.

    Always includes step 0 (first decision) and step -1 (final decision).
    Intermediate steps are evenly spaced to cover all phases.

    Training on multiple steps per rollout is critical: the original single
    last-step approach gives only 4 gradient signals per episode (one per G
    rollout). Multi-step gives ~20 signals, covering early phase decisions,
    mid-investigation choices, and the critical SAR-filing moment.
    """
    length = len(rollout["prompts"])
    if length <= n_train:
        return list(range(length))
    indices: List[int] = [0]
    for k in range(1, n_train - 1):
        idx = int(round(k * (length - 1) / (n_train - 1)))
        indices.append(idx)
    indices.append(length - 1)
    return sorted(set(indices))


# ---------------------------------------------------------------------------
# GRPO loss (core math — operates without TRL when testing)
# ---------------------------------------------------------------------------

def grpo_loss(
    model,
    tokenizer,
    prompts: List[str],
    completions: List[str],
    rewards: List[float],
) -> "torch.Tensor":
    """
    GRPO update step.

    For each (prompt, completion) pair:
        advantage_i = (reward_i - mean(rewards)) / (std(rewards) + eps)
        loss = -mean(advantage_i * log_prob(completion | prompt))

    Why GRPO: PPO requires value function unstable on sparse 50-step episodes.
    DPO needs curated pairs unavailable for novel adversarial schemes.
    GRPO operates from reward signal alone.
    """
    import torch

    device = next(model.parameters()).device
    rewards_t = torch.tensor(rewards, dtype=torch.float32, device=device)

    # Normalize rewards within the group (GRPO key operation)
    mean_r = rewards_t.mean()
    std_r  = rewards_t.std() + 1e-8
    advantages = (rewards_t - mean_r) / std_r

    total_loss = torch.tensor(0.0, device=device, requires_grad=True)
    valid_count = 0

    for i, (prompt, completion, adv) in enumerate(zip(prompts, completions, advantages)):
        full_text = prompt + completion
        inputs = tokenizer(
            full_text, return_tensors="pt", truncation=True, max_length=MAX_SEQ_LEN
        ).to(device)

        prompt_len = tokenizer(
            prompt, return_tensors="pt", truncation=True, max_length=MAX_SEQ_LEN
        )["input_ids"].shape[1]

        outputs = model(**inputs, labels=inputs["input_ids"])

        # Only count loss on completion tokens (not prompt)
        shift_logits  = outputs.logits[:, prompt_len-1:-1, :]
        shift_labels  = inputs["input_ids"][:, prompt_len:]

        # Skip if completion was truncated away entirely
        if shift_labels.shape[1] == 0:
            continue

        log_probs = torch.nn.functional.log_softmax(shift_logits, dim=-1)
        token_log_probs = log_probs.gather(
            2, shift_labels.unsqueeze(-1)
        ).squeeze(-1)

        # Mean log prob of completion
        mean_log_prob = token_log_probs.mean()

        # Skip NaN/Inf from extreme logits — don't let one bad step corrupt the batch
        if torch.isnan(mean_log_prob) or torch.isinf(mean_log_prob):
            continue

        # GRPO: maximize advantage-weighted log probability
        step_loss = -adv * mean_log_prob
        total_loss = total_loss + step_loss
        valid_count += 1

    # All steps were invalid — signal caller to skip update
    if valid_count == 0:
        return torch.tensor(float("nan"), device=device)

    return total_loss / valid_count


# ---------------------------------------------------------------------------
# Criminal Designer hook
# ---------------------------------------------------------------------------

def _maybe_update_criminal(criminal_designer, episode: int, episode_results: List[Dict]) -> None:
    """Every CODEX_UPDATE_K episodes, update the criminal's weakness database."""
    if criminal_designer is None:
        return
    if episode % CODEX_UPDATE_K != 0:
        return
    for res in episode_results[-CODEX_UPDATE_K:]:
        criminal_designer.update_weakness({
            "scheme_type": res.get("scheme_type", "smurfing"),
            "investigator_f1": res.get("f1", 0.5),
        })
    # Generate new scheme (will validate before adding to Codex)
    fn, info = criminal_designer.generate_and_validate()
    status = "validated" if info["validated"] else "failed"
    print(f"  [Codex] ep={episode} | target={info['target_weakness']} | {status} | novelty={info['novelty_bonus']:.3f}")


# ---------------------------------------------------------------------------
# CSV / JSON logging
# ---------------------------------------------------------------------------

def _init_csv(path: str) -> None:
    os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["episode", "scheme_type", "f1", "r_inv", "steps", "compliance"])


def _append_csv(path: str, episode: int, result: Dict) -> None:
    with open(path, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            episode,
            result.get("scheme_type", ""),
            f"{result.get('f1', 0):.4f}",
            f"{result.get('r_inv', 0):.4f}",
            result.get("steps", 0),
            f"{result.get('compliance', 0):.4f}",
        ])


def _save_curves(path: str, curves: Dict) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(curves, f, indent=2)


def _save_checkpoint(model, tokenizer, episode: int) -> None:
    ckpt_dir = os.path.join(OUT_DIR, f"ckpt_ep{episode:04d}")
    os.makedirs(ckpt_dir, exist_ok=True)
    model.save_pretrained(ckpt_dir)
    tokenizer.save_pretrained(ckpt_dir)
    print(f"  [Checkpoint] Saved to {ckpt_dir}")


# ---------------------------------------------------------------------------
# Main training loop
# ---------------------------------------------------------------------------

def train(
    num_episodes: int = NUM_EPISODES,
    use_trl_trainer: bool = True,   # False = lightweight manual loop (for CI)
    use_model: bool = True,          # False = heuristic rollouts (for CI without GPU)
    verbose: bool = True,
):
    """
    Full GRPO training loop.

    use_trl_trainer=True  → uses TRL GRPOConfig + standard update path
    use_trl_trainer=False → uses our manual grpo_loss() (same math, no TRL dep)
    use_model=False       → heuristic rollouts (testing/CI, no GPU required)
    """
    print("=" * 70)
    print("HEIST GRPO Training — Qwen2.5-1.5B (4-bit Unsloth)")
    print("=" * 70)
    print(f"  Episodes:      {num_episodes}")
    print(f"  GRPO G:        {GRPO_G} rollouts/prompt")
    print(f"  LR:            {LR}")
    print(f"  Codex update:  every {CODEX_UPDATE_K} episodes")
    print(f"  Checkpoint:    every {CKPT_EVERY} episodes -> {OUT_DIR}")
    if RESUME_FROM and os.path.exists(RESUME_FROM):
        print(f"  Resume from:   {RESUME_FROM}  (start_ep={START_EPISODE})")
    print()

    # ── Load model ─────────────────────────────────────────────────────
    model = tokenizer = optimizer = None

    if use_model:
        FastLanguageModel, torch, AutoTokenizer = _import_ml()

        if RESUME_FROM and os.path.exists(RESUME_FROM):
            # Resume from a saved checkpoint — LoRA adapters already merged into the
            # checkpoint, so we load directly without calling get_peft_model again.
            print(f"[1] Resuming from checkpoint: {RESUME_FROM}")
            model, tokenizer = FastLanguageModel.from_pretrained(
                model_name=RESUME_FROM,
                max_seq_length=MAX_SEQ_LEN,
                load_in_4bit=True,
                dtype=None,
            )
        else:
            print("[1] Loading Qwen2.5-1.5B with Unsloth 4-bit quantization...")
            model, tokenizer = FastLanguageModel.from_pretrained(
                model_name=MODEL_NAME,
                max_seq_length=MAX_SEQ_LEN,
                load_in_4bit=True,  # 4-bit for T4 (fits in 16GB VRAM)
                dtype=None,         # auto-detect bfloat16/float16
            )

            # LoRA adapters (PEFT — only fine-tune adapter layers)
            model = FastLanguageModel.get_peft_model(
                model,
                r=16,                       # LoRA rank
                target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                                 "gate_proj", "up_proj", "down_proj"],
                lora_alpha=16,
                lora_dropout=0,
                bias="none",
                use_gradient_checkpointing="unsloth",  # saves VRAM on T4
                random_state=42,
            )

        model.train()
        # Clear max_length from generation config so max_new_tokens doesn't
        # trigger the "Both max_new_tokens and max_length set" warning flood.
        if hasattr(model, "generation_config"):
            model.generation_config.max_length = None

        import torch
        optimizer = torch.optim.AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR,
        )
        print(f"  Model loaded. Trainable params: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    else:
        print("[1] Heuristic mode (no GPU) — model=None")

    # ── Setup env + agents ─────────────────────────────────────────────
    print("[2] Initialising HEIST environment...")
    env = HeistEnvironment()

    # Criminal Designer (optional — skipped if not importable)
    criminal_designer = None
    try:
        from agents.criminal import CriminalDesigner
        criminal_designer = CriminalDesigner(temperature=1.0, seed=42)
        print("  CriminalDesigner loaded.")
    except Exception as e:
        print(f"  CriminalDesigner not available: {e}")

    # Red Queen Curriculum (ELO-driven scheme selection)
    curriculum = RedQueenCurriculum()
    print("  RedQueenCurriculum loaded (ELO-driven scheme selection).")

    # Compliance Expert (preference drift — wired into run_rollout compliance score)
    expert = None
    try:
        sys.path.insert(0, os.path.join(_ROOT, "agents"))
        from agents.expert import ComplianceExpert
        expert = ComplianceExpert()
        print("  ComplianceExpert loaded.")
    except Exception as e:
        print(f"  ComplianceExpert not available: {e}")

    # ── Init logging ───────────────────────────────────────────────────
    os.makedirs(OUT_DIR, exist_ok=True)
    _init_csv(LOG_CSV)
    curves: Dict[str, Any] = {
        "episodes": [],
        "r_inv":    [],
        "f1":       [],
        "scheme_types": [],
        "config": {
            "model": MODEL_NAME,
            "num_episodes": num_episodes,
            "grpo_g": GRPO_G,
            "lr": LR,
        }
    }

    # ── Training loop ──────────────────────────────────────────────────
    start_ep = START_EPISODE
    end_ep   = start_ep + num_episodes - 1
    print(f"\n[3] Training for {num_episodes} episodes (ep {start_ep} → {end_ep})...\n")
    episode_results: List[Dict] = []

    for ep in range(start_ep, end_ep + 1):
        t0 = time.time()
        seed = ep * 17  # deterministic but varied seeds

        if verbose:
            print(f"Episode {ep:3d}/{num_episodes}", end="  ")

        # Red Queen: pick scheme type for this episode via ELO-weighted curriculum.
        # Previously env.reset() chose randomly → trade_based could dominate by luck.
        # Now the curriculum drives selection: high-ELO (hard) schemes sampled more.
        target_scheme = curriculum.select_scheme_type(ep)

        # Collect G rollouts (GRPO requires multiple samples per prompt)
        rollouts = []
        for g in range(GRPO_G):
            # Spread temperature across rollouts: 0.5 (conservative) → 0.9 (exploratory).
            # Capped at 0.9 (was 1.1) — values above ~1.0 produce near-zero-probability
            # completions that cause log(~0) → NaN loss, killing the gradient update.
            rollout_temp = 0.5 + (g / max(GRPO_G - 1, 1)) * 0.4
            # Don't pass expert to rollouts — ComplianceExpert burns ~1400 Groq tokens
            # per call × 6 rollouts × 50 episodes = 420k tokens, exhausting the 500k/day
            # limit by ep35. Expert compliance is kept for the best-rollout log only.
            rollout = run_rollout(
                env=env,
                model=model,
                tokenizer=tokenizer,
                seed=seed + g,
                use_model=use_model,
                verbose=False,
                expert=None,
                episode_num=ep,
                temperature=rollout_temp,
                preferred_scheme_type=target_scheme,
            )
            rollouts.append(rollout)

        # Use best rollout for logging (mean r_inv across group)
        mean_r_inv = float(np.mean([r["r_inv"] for r in rollouts]))
        best_rollout = max(rollouts, key=lambda x: x["r_inv"])

        # ── GRPO update ────────────────────────────────────────────────
        if use_model and model is not None and optimizer is not None:
            # GRPO: normalize across the G rollouts by their terminal R_inv.
            # Each rollout is treated as one group member — advantage computed
            # from final episode reward so intermediate steps aren't penalized.
            import torch
            # Terminal reward signal for GRPO advantage computation.
            # - SAR filed (compliance > 0): use rewards[-1] = env_step_r + r_inv,
            #   which includes the compliance × 10 bonus. Range ~1.0–5.0, std ~1.0.
            # - Timeout (no SAR filed, compliance == 0): rewards[-1] is just the
            #   last wandering step's env reward + low r_inv — semantically ambiguous.
            #   Replace with a fixed -0.5 penalty so GRPO learns timeout = bad,
            #   not "a slightly different kind of good rollout".
            rollout_rewards = [
                (r["rewards"][-1] if r["rewards"] else r["r_inv"])
                if r["compliance"] > 0
                else -0.5
                for r in rollouts
            ]
            rewards_t = torch.tensor(rollout_rewards, dtype=torch.float32)
            mean_r = rewards_t.mean()
            std_r  = rewards_t.std() + 1e-8
            advantages = ((rewards_t - mean_r) / std_r).tolist()

            optimizer.zero_grad()
            # Multi-step GRPO: 5 key steps per rollout (first, 3 intermediates, last)
            # Previously only trained on last step — now 5x more gradient signal per episode,
            # covering early-phase decisions + the critical SARFiling moment.
            all_prompts: List[str] = []
            all_completions: List[str] = []
            all_advantages: List[float] = []
            for rollout_i, adv_i in zip(rollouts, advantages):
                key_steps = _sample_key_steps(rollout_i, n_train=5)
                for si in key_steps:
                    all_prompts.append(rollout_i["prompts"][si])
                    all_completions.append(rollout_i["completions"][si])
                    all_advantages.append(float(adv_i))
            total_loss = grpo_loss(
                model, tokenizer,
                all_prompts,
                all_completions,
                all_advantages,
            )
            # Skip update if loss is NaN/Inf — high-temperature rollouts can produce
            # near-zero-probability completions causing log(~0) → -inf → NaN.
            # Propagating NaN gradients corrupts model weights silently.
            if torch.isnan(total_loss) or torch.isinf(total_loss):
                if verbose:
                    print(f"  [WARN] NaN/Inf loss — skipping gradient update this episode")
                loss_val = float("nan")
            else:
                total_loss.backward()
                torch.nn.utils.clip_grad_norm_(
                    [p for p in model.parameters() if p.requires_grad], max_norm=0.5
                )
                optimizer.step()
                loss_val = float(total_loss.item())
        else:
            loss_val = 0.0

        elapsed = time.time() - t0

        if verbose:
            entropy_str = f"| H(a)={best_rollout.get('action_entropy', 0):.2f} "
            print(
                f"| scheme={best_rollout['scheme_type']:12s} "
                f"| R_inv={mean_r_inv:.3f} "
                f"| F1={best_rollout['f1']:.3f} "
                f"| steps={best_rollout['steps']:2d} "
                f"| loss={loss_val:.4f} "
                f"{entropy_str}"
                f"| {elapsed:.1f}s"
            )

        # ── Update Red Queen curriculum with episode result ────────────
        curriculum.update({
            "scheme_type":    best_rollout["scheme_type"],
            "f1":             best_rollout["f1"],
            "morph_succeeded": False,
            "novel_evaded":    False,
        })

        # ── Log ────────────────────────────────────────────────────────
        episode_results.append(best_rollout)
        _append_csv(LOG_CSV, ep, {**best_rollout, "r_inv": mean_r_inv})

        curves["episodes"].append(ep)
        curves["r_inv"].append(round(mean_r_inv, 4))
        curves["f1"].append(round(best_rollout["f1"], 4))
        curves["scheme_types"].append(best_rollout["scheme_type"])

        # ── Dynamic exploration: bump temperature when performance drops ──
        # Only escalate when >10% below rolling average (was 5% — too sensitive,
        # fired 22% of episodes and kept temperature pinned at 1.5 cap).
        # Cool faster: 0.93/ep instead of 0.97/ep (recovers in ~8 eps not 17).
        if criminal_designer is not None and ep > 5:
            recent_rinvs = curves["r_inv"][-5:]
            rolling_avg = float(np.mean(recent_rinvs)) if recent_rinvs else 0.0
            if rolling_avg > 0 and mean_r_inv < rolling_avg * 0.90:
                criminal_designer.temperature = min(1.5, criminal_designer.temperature * 1.2)
                if verbose:
                    print(f"  [Explore] Perf drop detected (R={mean_r_inv:.3f} < avg={rolling_avg:.3f}) — temperature={criminal_designer.temperature:.2f}")
            else:
                criminal_designer.temperature = max(1.0, criminal_designer.temperature * 0.93)

        # ── Criminal Codex update ──────────────────────────────────────
        #    Every K=5 episodes, call criminal.adapt() to evolve the criminal
        _maybe_update_criminal(criminal_designer, ep, episode_results)

        # ── Checkpoint ─────────────────────────────────────────────────
        if use_model and model is not None and ep % CKPT_EVERY == 0:
            _save_checkpoint(model, tokenizer, ep)

    # ── Save reward curve ──────────────────────────────────────────────
    _save_curves(CURVES_PATH, curves)
    print(f"\n[4] Training complete.")
    print(f"  Reward curve saved to {CURVES_PATH}")
    print(f"  Per-scheme F1 log  saved to {LOG_CSV}")
    if use_model:
        print(f"  Checkpoints in {OUT_DIR}")

    # ── Interpretability summary ───────────────────────────────────────
    entropies = [r.get("action_entropy", 0.0) for r in episode_results if r.get("action_entropy") is not None]
    if entropies:
        first5  = float(np.mean(entropies[:5]))
        last5   = float(np.mean(entropies[-5:]))
        print(f"\n  [Interpretability] Action entropy:")
        print(f"    First 5 eps avg:  H={first5:.3f}  (higher = more random)")
        print(f"    Last  5 eps avg:  H={last5:.3f}  (lower  = more decisive)")
        if last5 < first5 - 0.05:
            print(f"    ✓ Agent became MORE decisive over training (ΔH={last5-first5:.3f})")
        else:
            print(f"    ~ No clear decisiveness improvement (ΔH={last5-first5:.3f})")

    # ── Final ELO table ────────────────────────────────────────────────
    print(f"\n  [RedQueen] Final ELO standings:")
    print(curriculum.scheme_elo_table())

    # ── Zero-Day synthesis ─────────────────────────────────────────────
    # Synthesize a coordinated attack from the 3 hardest schemes (by ELO).
    # This scheme is engineered from the investigator's own failure modes.
    if criminal_designer is not None:
        top3 = curriculum.top_schemes_by_elo(n=3)
        print(f"\n  [ZeroDay] Synthesizing from top-ELO schemes: {top3}")
        zd_fn, zd_info = criminal_designer.synthesize_zero_day(top3, episode_number=end_ep)
        if zd_info.get("validated"):
            print(f"  [ZeroDay] ✓ Validated. Structural novelty={zd_info['novelty_bonus']:.3f}")
            # Run 2 heuristic rollouts against the Zero-Day to measure baseline detection
            print(f"  [ZeroDay] Running heuristic detection eval...")
            zd_f1_scores = []
            for zd_seed in [7777, 8888]:
                zd_rollout = run_rollout(
                    env=env, model=None, tokenizer=None,
                    seed=zd_seed, use_model=False, verbose=False,
                    expert=None, episode_num=end_ep,
                )
                zd_f1_scores.append(zd_rollout["f1"])
            zd_f1 = float(np.mean(zd_f1_scores))

            # Compare against mean F1 on known schemes
            known_f1 = float(np.mean(curves["f1"][-10:])) if curves["f1"] else 0.0
            print(f"  [ZeroDay] Heuristic F1 on Zero-Day: {zd_f1:.3f}")
            print(f"  [ZeroDay] Known-scheme F1 (last 10 ep): {known_f1:.3f}")
            gap = known_f1 - zd_f1
            if gap > 0.05:
                print(f"  [ZeroDay] ✓ F1 gap = {gap:.3f} — Zero-Day harder than known schemes!")
            else:
                print(f"  [ZeroDay] ~ F1 gap = {gap:.3f} — Zero-Day not significantly harder")
        else:
            print(f"  [ZeroDay] Generation failed: {zd_info.get('validation_error', 'unknown')}")

    # Summary stats
    r_invs = curves["r_inv"]
    if r_invs:
        print(f"\n  R_investigator:  first={r_invs[0]:.3f}  last={r_invs[-1]:.3f}  "
              f"max={max(r_invs):.3f}  mean={sum(r_invs)/len(r_invs):.3f}")

    return curves


# ---------------------------------------------------------------------------
# Dry-run mode (no GPU — validates the rollout pipeline)
# ---------------------------------------------------------------------------

def dry_run(num_episodes: int = 3) -> None:
    """
    Validate the full training pipeline without a GPU.
    Runs heuristic rollouts to prove env / reward / CSV / JSON plumbing works.
    """
    print("=" * 70)
    print("HEIST GRPO — Dry Run (heuristic rollouts, no GPU)")
    print("=" * 70)
    curves = train(
        num_episodes=num_episodes,
        use_trl_trainer=False,
        use_model=False,
        verbose=True,
    )
    print("\n[DRY RUN] Pipeline verified:")
    print(f"  Episodes run: {len(curves['episodes'])}")
    print(f"  R_inv values: {curves['r_inv']}")
    print(f"  Scheme types: {curves['scheme_types']}")

    # Verify output files
    assert os.path.exists(CURVES_PATH), f"Missing {CURVES_PATH}"
    assert os.path.exists(LOG_CSV),     f"Missing {LOG_CSV}"
    with open(CURVES_PATH, encoding="utf-8") as f:
        saved = json.load(f)
    assert len(saved["episodes"]) == num_episodes
    print(f"  training_curves.json: OK ({len(saved['episodes'])} entries)")
    print(f"  training_log.csv: OK")
    print("\nDry run PASSED — ready for Colab T4 training.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="HEIST GRPO Training")
    parser.add_argument("--dry-run",      action="store_true", help="Run without GPU (heuristic rollouts)")
    parser.add_argument("--episodes",     type=int, default=NUM_EPISODES)
    parser.add_argument("--no-trl",       action="store_true", help="Use manual GRPO loss instead of TRL")
    parser.add_argument("--quiet",        action="store_true")
    args = parser.parse_args()

    if args.dry_run:
        dry_run(num_episodes=args.episodes)
    else:
        train(
            num_episodes=args.episodes,
            use_trl_trainer=not args.no_trl,
            use_model=True,
            verbose=not args.quiet,
        )
