"""
HEIST GRPO Training Script — Step 11.

Why GRPO?
---------
PPO requires a value function (critic) that is unstable on sparse 50-step episodes
where reward only arrives when the SAR is finally filed. DPO needs curated
preference pairs which do not exist for novel adversarial schemes generated by the
Criminal Codex at runtime. GRPO operates from the reward signal alone: it samples
G rollouts per prompt, normalises them within the group, and updates the policy
without a critic — exactly what a sparse multi-step investigator reward demands.

Architecture
------------
Observation  →  prompt text  →  Qwen2.5-1.5B (4-bit, Unsloth)  →  action token
Action token →  HeistEnvironment.step()  →  next observation + reward
Episode done →  R_investigator computed  →  GRPO loss  →  gradient update

Files written
-------------
checkpoints/ckpt_ep{N}/     — model + tokenizer every 10 episodes
training_curves.json        — reward curve (episode -> R_investigator)
training_log.csv            — per-episode per-scheme-type F1 (for Red Queen)
"""

from __future__ import annotations

import csv
import json
import os
import sys
import time
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

# ---------------------------------------------------------------------------
# Resolve project root so env/ and agents/ imports work from train/
# ---------------------------------------------------------------------------
_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
_ENV  = os.path.join(_ROOT, "env")
for _p in [_ROOT, _ENV]:
    if _p not in sys.path:
        sys.path.insert(0, _p)

# ---------------------------------------------------------------------------
# Lazy imports — heavy ML deps only needed on Colab/GPU machine
# ---------------------------------------------------------------------------
def _import_ml():
    """Import ML stack lazily so env-only tests don't fail without GPU."""
    try:
        from unsloth import FastLanguageModel
        import torch
        from transformers import AutoTokenizer
        return FastLanguageModel, torch, AutoTokenizer
    except ImportError as e:
        raise ImportError(
            f"Missing ML dependency: {e}\n"
            "Install with: pip install unsloth transformers torch"
        ) from e

# ---------------------------------------------------------------------------
# Env imports (always available)
# ---------------------------------------------------------------------------
from heist_env import HeistEnvironment
from models import InvestigatorAction, ActionType
from reward import r_investigator

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

MODEL_NAME      = os.environ.get("HEIST_MODEL",      "unsloth/Qwen2.5-1.5B-Instruct-bnb-4bit")
MAX_SEQ_LEN     = int(os.environ.get("MAX_SEQ_LEN",  "2048"))
NUM_EPISODES    = int(os.environ.get("NUM_EPISODES",  "20"))    # 20 for T4 smoke run
GRPO_G          = int(os.environ.get("GRPO_G",       "4"))      # rollouts per prompt
LR              = float(os.environ.get("LR",          "5e-5"))
CODEX_UPDATE_K  = int(os.environ.get("CODEX_K",      "5"))      # criminal.adapt() every K eps
CKPT_EVERY      = int(os.environ.get("CKPT_EVERY",   "10"))     # checkpoint interval
OUT_DIR         = os.environ.get("OUT_DIR",           os.path.join(_ROOT, "checkpoints"))
CURVES_PATH     = os.environ.get("CURVES_PATH",       os.path.join(_ROOT, "training_curves.json"))
LOG_CSV         = os.environ.get("LOG_CSV",           os.path.join(_ROOT, "training_log.csv"))

# Action vocabulary the model can emit
ACTION_VOCAB = [
    "query_transactions",
    "trace_network",
    "lookup_entity",
    "cross_reference_jurisdiction",
    "request_subpoena",
    "file_SAR",
]

_ACTION_MAP = {
    "query_transactions":           ActionType.QUERY_TRANSACTIONS,
    "trace_network":                ActionType.TRACE_NETWORK,
    "lookup_entity":                ActionType.LOOKUP_ENTITY,
    "cross_reference_jurisdiction": ActionType.CROSS_REFERENCE,
    "request_subpoena":             ActionType.REQUEST_SUBPOENA,
    "file_SAR":                     ActionType.FILE_SAR,
}

# ---------------------------------------------------------------------------
# Prompt / response formatting
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = (
    "You are an AML investigator. Analyse the observation and choose ONE action.\n"
    "Available actions: " + ", ".join(ACTION_VOCAB) + ".\n"
    "Reply with EXACTLY: ACTION:<action_name> ENTITY:<entity_id>\n"
    "For file_SAR reply: ACTION:file_SAR ENTITIES:<e1>,<e2>,<e3>"
)


def obs_to_prompt(obs_dict: Dict[str, Any]) -> str:
    """Format a HeistObservation dict into a text prompt."""
    phase   = obs_dict.get("current_phase", "AlertTriage")
    budget  = obs_dict.get("budget_remaining", 50)
    beliefs = obs_dict.get("bayesian_beliefs", {})
    flagged = obs_dict.get("flagged_transaction") or {}
    morph   = obs_dict.get("morph_alert", {})

    # Top-3 suspicious entities
    top3 = sorted(beliefs.items(), key=lambda x: -x[1])[:3]
    belief_str = " | ".join(f"{e}={p:.2f}" for e, p in top3) or "none"

    flagged_str = (
        f"{flagged.get('source_entity','?')} -> {flagged.get('target_entity','?')}"
        f" ${flagged.get('amount', 0):.0f}"
        if flagged else "none"
    )

    morph_str = f"MORPH_ALERT invalidated={morph.get('invalidated_entities', [])}" if morph.get("morph_occurred") else ""

    return (
        f"[PHASE:{phase}] [BUDGET:{budget}]\n"
        f"FLAGGED: {flagged_str}\n"
        f"TOP_SUSPECTS: {belief_str}\n"
        f"{morph_str}\n"
        "CHOOSE ACTION:"
    )


def parse_action(text: str, beliefs: Dict[str, float]) -> Tuple[str, Dict[str, Any]]:
    """
    Parse model output into (action_type, params).
    Gracefully falls back to heuristic if parsing fails.
    """
    import re
    text = text.strip()

    # Try structured parse
    action_match = re.search(r"ACTION:(\w+)", text)
    entity_match = re.search(r"ENTITY:(\S+)", text)
    entities_match = re.search(r"ENTITIES:([\w,_\-]+)", text)

    if not action_match:
        # Fallback: first action keyword found in text
        for act in ACTION_VOCAB:
            if act in text:
                action_match_str = act
                break
        else:
            action_match_str = "query_transactions"
    else:
        action_match_str = action_match.group(1)

    # Normalise action name
    action_type = action_match_str.strip()
    if action_type not in ACTION_VOCAB:
        action_type = "query_transactions"

    # Entity
    if action_type == "file_SAR":
        if entities_match:
            entities = entities_match.group(1).split(",")
        else:
            entities = list(beliefs.keys())[:5]
        return action_type, {"evidence_chain": entities}
    else:
        if entity_match:
            entity = entity_match.group(1)
        elif beliefs:
            entity = max(beliefs, key=beliefs.get)
        else:
            entity = ""
        return action_type, {"entity_id": entity}


# ---------------------------------------------------------------------------
# Rollout: run one episode, return trajectory
# ---------------------------------------------------------------------------

def run_rollout(
    env: HeistEnvironment,
    model,
    tokenizer,
    seed: int,
    use_model: bool = True,
    verbose: bool = False,
) -> Dict[str, Any]:
    """
    Run one complete episode.

    Returns a dict with:
        prompts:     List[str]   — text prompt at each step
        completions: List[str]   — model output at each step
        rewards:     List[float] — step reward (0 except last = R_investigator)
        r_inv:       float       — final R_investigator score
        scheme_type: str
        f1_by_type:  Dict[str, float]
    """
    obs = env.reset(seed=seed)
    obs_dict = obs.model_dump()
    scheme_type = obs_dict.get("metadata", {}).get("scheme_type", "unknown")

    prompts:     List[str]   = []
    completions: List[str]   = []
    step_rewards: List[float] = []
    evidence_chain: List[str] = []
    subpoenaed: set = set()

    done = False
    steps = 0
    final_compliance = 0.0
    final_beliefs: Dict[str, float] = {}

    while not done and steps < 50:
        steps += 1
        prompt_text = obs_dict_to_full_prompt(obs_dict)
        beliefs = obs_dict.get("bayesian_beliefs", {})

        if use_model and model is not None:
            # Generate one action token sequence
            inputs = tokenizer(
                prompt_text, return_tensors="pt", truncation=True, max_length=MAX_SEQ_LEN
            )
            import torch
            device = next(model.parameters()).device
            inputs = {k: v.to(device) for k, v in inputs.items()}
            with torch.no_grad():
                outputs = model.generate(
                    **inputs,
                    max_new_tokens=40,
                    do_sample=True,
                    temperature=0.7,
                    pad_token_id=tokenizer.eos_token_id,
                )
            generated = tokenizer.decode(
                outputs[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True
            )
        else:
            # Heuristic fallback (for testing without GPU)
            generated = _heuristic_action_text(obs_dict)

        action_type_str, params = parse_action(generated, beliefs)

        # Accumulate evidence
        entity = params.get("entity_id", "")
        if entity and entity not in evidence_chain:
            evidence_chain.append(entity)

        # Step
        action = InvestigatorAction(
            action_type=_ACTION_MAP.get(action_type_str, ActionType.QUERY_TRANSACTIONS),
            params=params,
        )
        obs = env.step(action)
        obs_dict = obs.model_dump()

        # Immediate step reward
        step_r = float(obs_dict.get("reward", 0.0))

        prompts.append(prompt_text)
        completions.append(generated)
        step_rewards.append(step_r)

        done = bool(obs_dict.get("done", False))
        final_beliefs = obs_dict.get("bayesian_beliefs", {})

        # Compliance score from SAR
        tool_result = obs_dict.get("tool_result") or {}
        data = tool_result.get("data", {})
        if "compliance_score" in data:
            final_compliance = float(data["compliance_score"])

        if verbose:
            print(f"  step={steps:2d} | {action_type_str:30s} | R={step_r:+.2f} | budget={obs_dict.get('budget_remaining')}")

    gt = env._graph.ground_truth.get(env.state.scheme_id, {})
    true_path  = list(gt.get("full_path", []))
    scheme_t   = gt.get("scheme_type", scheme_type)

    r_inv_result = r_investigator(
        evidence_chain=evidence_chain,
        ground_truth_path=true_path,
        compliance_score=final_compliance,
        queries_used=steps,
        total_budget=50,
        query_history=env.state.query_history,
        graph=env._graph,
        scheme_type=scheme_t,
        is_codex_generated=False,
    )
    r_inv = float(r_inv_result["total"])

    # Assign terminal reward to last step only (sparse)
    if step_rewards:
        step_rewards[-1] += r_inv

    # Scheme-type F1 (for Red Queen curriculum CSV)
    predicted_set = set(evidence_chain)
    true_set = set(true_path)
    if true_set:
        tp = len(predicted_set & true_set)
        precision = tp / max(len(predicted_set), 1)
        recall    = tp / max(len(true_set), 1)
        f1 = 2 * precision * recall / max(precision + recall, 1e-9)
    else:
        f1 = 0.0

    return {
        "prompts":     prompts,
        "completions": completions,
        "rewards":     step_rewards,
        "r_inv":       r_inv,
        "scheme_type": scheme_type,
        "f1":          f1,
        "f1_by_type":  {scheme_type: f1},
        "steps":       steps,
        "compliance":  final_compliance,
    }


def obs_dict_to_full_prompt(obs_dict: Dict[str, Any]) -> str:
    """Full prompt with system + observation."""
    return f"{SYSTEM_PROMPT}\n\n{obs_to_prompt(obs_dict)}"


def _heuristic_action_text(obs_dict: Dict[str, Any]) -> str:
    """Return a heuristic action in model output format (no GPU needed)."""
    phase   = obs_dict.get("current_phase", "AlertTriage")
    beliefs = obs_dict.get("bayesian_beliefs", {})
    flagged = obs_dict.get("flagged_transaction") or {}

    entity = (
        max(beliefs, key=beliefs.get)
        if beliefs
        else flagged.get("source_entity", "unknown")
    )

    phase_actions = {
        "AlertTriage":    "query_transactions",
        "Investigation":  "trace_network",
        "CrossReference": "cross_reference_jurisdiction",
        "SARFiling":      "file_SAR",
    }
    act = phase_actions.get(phase, "query_transactions")

    if act == "file_SAR":
        entities = ",".join(list(beliefs.keys())[:5])
        return f"ACTION:file_SAR ENTITIES:{entities}"
    return f"ACTION:{act} ENTITY:{entity}"


# ---------------------------------------------------------------------------
# GRPO loss (core math — operates without TRL when testing)
# ---------------------------------------------------------------------------

def grpo_loss(
    model,
    tokenizer,
    prompts: List[str],
    completions: List[str],
    rewards: List[float],
) -> "torch.Tensor":
    """
    GRPO update step.

    For each (prompt, completion) pair:
        advantage_i = (reward_i - mean(rewards)) / (std(rewards) + eps)
        loss = -mean(advantage_i * log_prob(completion | prompt))

    Why GRPO: PPO requires value function unstable on sparse 50-step episodes.
    DPO needs curated pairs unavailable for novel adversarial schemes.
    GRPO operates from reward signal alone.
    """
    import torch

    device = next(model.parameters()).device
    rewards_t = torch.tensor(rewards, dtype=torch.float32, device=device)

    # Normalize rewards within the group (GRPO key operation)
    mean_r = rewards_t.mean()
    std_r  = rewards_t.std() + 1e-8
    advantages = (rewards_t - mean_r) / std_r

    total_loss = torch.tensor(0.0, device=device, requires_grad=True)

    for i, (prompt, completion, adv) in enumerate(zip(prompts, completions, advantages)):
        full_text = prompt + completion
        inputs = tokenizer(
            full_text, return_tensors="pt", truncation=True, max_length=MAX_SEQ_LEN
        ).to(device)

        prompt_len = tokenizer(
            prompt, return_tensors="pt", truncation=True, max_length=MAX_SEQ_LEN
        )["input_ids"].shape[1]

        outputs = model(**inputs, labels=inputs["input_ids"])

        # Only count loss on completion tokens (not prompt)
        shift_logits  = outputs.logits[:, prompt_len-1:-1, :]
        shift_labels  = inputs["input_ids"][:, prompt_len:]

        log_probs = torch.nn.functional.log_softmax(shift_logits, dim=-1)
        token_log_probs = log_probs.gather(
            2, shift_labels.unsqueeze(-1)
        ).squeeze(-1)

        # Mean log prob of completion
        mean_log_prob = token_log_probs.mean()

        # GRPO: maximize advantage-weighted log probability
        step_loss = -adv * mean_log_prob
        total_loss = total_loss + step_loss / len(prompts)

    return total_loss


# ---------------------------------------------------------------------------
# Criminal Designer hook
# ---------------------------------------------------------------------------

def _maybe_update_criminal(criminal_designer, episode: int, episode_results: List[Dict]) -> None:
    """Every CODEX_UPDATE_K episodes, update the criminal's weakness database."""
    if criminal_designer is None:
        return
    if episode % CODEX_UPDATE_K != 0:
        return
    for res in episode_results[-CODEX_UPDATE_K:]:
        criminal_designer.update_weakness({
            "scheme_type": res.get("scheme_type", "smurfing"),
            "investigator_f1": res.get("f1", 0.5),
        })
    # Generate new scheme (will validate before adding to Codex)
    fn, info = criminal_designer.generate_and_validate()
    status = "validated" if info["validated"] else "failed"
    print(f"  [Codex] ep={episode} | target={info['target_weakness']} | {status} | novelty={info['novelty_bonus']:.3f}")


# ---------------------------------------------------------------------------
# CSV / JSON logging
# ---------------------------------------------------------------------------

def _init_csv(path: str) -> None:
    os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["episode", "scheme_type", "f1", "r_inv", "steps", "compliance"])


def _append_csv(path: str, episode: int, result: Dict) -> None:
    with open(path, "a", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow([
            episode,
            result.get("scheme_type", ""),
            f"{result.get('f1', 0):.4f}",
            f"{result.get('r_inv', 0):.4f}",
            result.get("steps", 0),
            f"{result.get('compliance', 0):.4f}",
        ])


def _save_curves(path: str, curves: Dict) -> None:
    with open(path, "w", encoding="utf-8") as f:
        json.dump(curves, f, indent=2)


def _save_checkpoint(model, tokenizer, episode: int) -> None:
    ckpt_dir = os.path.join(OUT_DIR, f"ckpt_ep{episode:04d}")
    os.makedirs(ckpt_dir, exist_ok=True)
    model.save_pretrained(ckpt_dir)
    tokenizer.save_pretrained(ckpt_dir)
    print(f"  [Checkpoint] Saved to {ckpt_dir}")


# ---------------------------------------------------------------------------
# Main training loop
# ---------------------------------------------------------------------------

def train(
    num_episodes: int = NUM_EPISODES,
    use_trl_trainer: bool = True,   # False = lightweight manual loop (for CI)
    use_model: bool = True,          # False = heuristic rollouts (for CI without GPU)
    verbose: bool = True,
):
    """
    Full GRPO training loop.

    use_trl_trainer=True  → uses TRL GRPOConfig + standard update path
    use_trl_trainer=False → uses our manual grpo_loss() (same math, no TRL dep)
    use_model=False       → heuristic rollouts (testing/CI, no GPU required)
    """
    print("=" * 70)
    print("HEIST GRPO Training — Qwen2.5-1.5B (4-bit Unsloth)")
    print("=" * 70)
    print(f"  Episodes:      {num_episodes}")
    print(f"  GRPO G:        {GRPO_G} rollouts/prompt")
    print(f"  LR:            {LR}")
    print(f"  Codex update:  every {CODEX_UPDATE_K} episodes")
    print(f"  Checkpoint:    every {CKPT_EVERY} episodes -> {OUT_DIR}")
    print()

    # ── Load model ─────────────────────────────────────────────────────
    model = tokenizer = optimizer = None

    if use_model:
        FastLanguageModel, torch, AutoTokenizer = _import_ml()

        print("[1] Loading Qwen2.5-1.5B with Unsloth 4-bit quantization...")
        model, tokenizer = FastLanguageModel.from_pretrained(
            model_name=MODEL_NAME,
            max_seq_length=MAX_SEQ_LEN,
            load_in_4bit=True,  # 4-bit for T4 (fits in 16GB VRAM)
            dtype=None,         # auto-detect bfloat16/float16
        )

        # LoRA adapters (PEFT — only fine-tune adapter layers)
        model = FastLanguageModel.get_peft_model(
            model,
            r=16,                       # LoRA rank
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                             "gate_proj", "up_proj", "down_proj"],
            lora_alpha=16,
            lora_dropout=0,
            bias="none",
            use_gradient_checkpointing="unsloth",  # saves VRAM on T4
            random_state=42,
        )

        model.train()

        import torch
        optimizer = torch.optim.AdamW(
            [p for p in model.parameters() if p.requires_grad],
            lr=LR,
        )
        print(f"  Model loaded. Trainable params: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")
    else:
        print("[1] Heuristic mode (no GPU) — model=None")

    # ── Setup env + agents ─────────────────────────────────────────────
    print("[2] Initialising HEIST environment...")
    env = HeistEnvironment()

    # Criminal Designer (optional — skipped if not importable)
    criminal_designer = None
    try:
        from agents.criminal import CriminalDesigner
        criminal_designer = CriminalDesigner(temperature=1.0, seed=42)
        print("  CriminalDesigner loaded.")
    except Exception as e:
        print(f"  CriminalDesigner not available: {e}")

    # ── Init logging ───────────────────────────────────────────────────
    os.makedirs(OUT_DIR, exist_ok=True)
    _init_csv(LOG_CSV)
    curves: Dict[str, Any] = {
        "episodes": [],
        "r_inv":    [],
        "f1":       [],
        "scheme_types": [],
        "config": {
            "model": MODEL_NAME,
            "num_episodes": num_episodes,
            "grpo_g": GRPO_G,
            "lr": LR,
        }
    }

    # ── Training loop ──────────────────────────────────────────────────
    print(f"\n[3] Training for {num_episodes} episodes...\n")
    episode_results: List[Dict] = []

    for ep in range(1, num_episodes + 1):
        t0 = time.time()
        seed = ep * 17  # deterministic but varied seeds

        if verbose:
            print(f"Episode {ep:3d}/{num_episodes}", end="  ")

        # Collect G rollouts (GRPO requires multiple samples per prompt)
        rollouts = []
        for g in range(GRPO_G):
            rollout = run_rollout(
                env=env,
                model=model,
                tokenizer=tokenizer,
                seed=seed + g,
                use_model=use_model,
                verbose=False,
            )
            rollouts.append(rollout)

        # Use best rollout for logging (mean r_inv across group)
        mean_r_inv = float(np.mean([r["r_inv"] for r in rollouts]))
        best_rollout = max(rollouts, key=lambda x: x["r_inv"])

        # ── GRPO update ────────────────────────────────────────────────
        if use_model and model is not None and optimizer is not None:
            # GRPO: normalize across the G rollouts by their terminal R_inv.
            # Each rollout is treated as one group member — advantage computed
            # from final episode reward so intermediate steps aren't penalized.
            import torch
            rollout_rewards = [r["r_inv"] for r in rollouts]
            rewards_t = torch.tensor(rollout_rewards, dtype=torch.float32)
            mean_r = rewards_t.mean()
            std_r  = rewards_t.std() + 1e-8
            advantages = ((rewards_t - mean_r) / std_r).tolist()

            optimizer.zero_grad()
            # One gradient contribution per rollout (last step = SAR decision)
            total_loss = grpo_loss(
                model, tokenizer,
                [r["prompts"][-1]      for r in rollouts],
                [r["completions"][-1]  for r in rollouts],
                advantages,
            )
            total_loss.backward()
            # Gradient clipping (stability on sparse rewards)
            torch.nn.utils.clip_grad_norm_(
                [p for p in model.parameters() if p.requires_grad], max_norm=1.0
            )
            optimizer.step()
            loss_val = float(total_loss.item())
        else:
            loss_val = 0.0

        elapsed = time.time() - t0

        if verbose:
            print(
                f"| scheme={best_rollout['scheme_type']:12s} "
                f"| R_inv={mean_r_inv:.3f} "
                f"| F1={best_rollout['f1']:.3f} "
                f"| steps={best_rollout['steps']:2d} "
                f"| loss={loss_val:.4f} "
                f"| {elapsed:.1f}s"
            )

        # ── Log ────────────────────────────────────────────────────────
        episode_results.append(best_rollout)
        _append_csv(LOG_CSV, ep, {**best_rollout, "r_inv": mean_r_inv})

        curves["episodes"].append(ep)
        curves["r_inv"].append(round(mean_r_inv, 4))
        curves["f1"].append(round(best_rollout["f1"], 4))
        curves["scheme_types"].append(best_rollout["scheme_type"])

        # ── Criminal Codex update ──────────────────────────────────────
        #    Every K=5 episodes, call criminal.adapt() to evolve the criminal
        _maybe_update_criminal(criminal_designer, ep, episode_results)

        # ── Checkpoint ─────────────────────────────────────────────────
        if use_model and model is not None and ep % CKPT_EVERY == 0:
            _save_checkpoint(model, tokenizer, ep)

    # ── Save reward curve ──────────────────────────────────────────────
    _save_curves(CURVES_PATH, curves)
    print(f"\n[4] Training complete.")
    print(f"  Reward curve saved to {CURVES_PATH}")
    print(f"  Per-scheme F1 log  saved to {LOG_CSV}")
    if use_model:
        print(f"  Checkpoints in {OUT_DIR}")

    # Summary stats
    r_invs = curves["r_inv"]
    if r_invs:
        print(f"\n  R_investigator:  first={r_invs[0]:.3f}  last={r_invs[-1]:.3f}  "
              f"max={max(r_invs):.3f}  mean={sum(r_invs)/len(r_invs):.3f}")

    return curves


# ---------------------------------------------------------------------------
# Dry-run mode (no GPU — validates the rollout pipeline)
# ---------------------------------------------------------------------------

def dry_run(num_episodes: int = 3) -> None:
    """
    Validate the full training pipeline without a GPU.
    Runs heuristic rollouts to prove env / reward / CSV / JSON plumbing works.
    """
    print("=" * 70)
    print("HEIST GRPO — Dry Run (heuristic rollouts, no GPU)")
    print("=" * 70)
    curves = train(
        num_episodes=num_episodes,
        use_trl_trainer=False,
        use_model=False,
        verbose=True,
    )
    print("\n[DRY RUN] Pipeline verified:")
    print(f"  Episodes run: {len(curves['episodes'])}")
    print(f"  R_inv values: {curves['r_inv']}")
    print(f"  Scheme types: {curves['scheme_types']}")

    # Verify output files
    assert os.path.exists(CURVES_PATH), f"Missing {CURVES_PATH}"
    assert os.path.exists(LOG_CSV),     f"Missing {LOG_CSV}"
    with open(CURVES_PATH, encoding="utf-8") as f:
        saved = json.load(f)
    assert len(saved["episodes"]) == num_episodes
    print(f"  training_curves.json: OK ({len(saved['episodes'])} entries)")
    print(f"  training_log.csv: OK")
    print("\nDry run PASSED — ready for Colab T4 training.")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="HEIST GRPO Training")
    parser.add_argument("--dry-run",      action="store_true", help="Run without GPU (heuristic rollouts)")
    parser.add_argument("--episodes",     type=int, default=NUM_EPISODES)
    parser.add_argument("--no-trl",       action="store_true", help="Use manual GRPO loss instead of TRL")
    parser.add_argument("--quiet",        action="store_true")
    args = parser.parse_args()

    if args.dry_run:
        dry_run(num_episodes=args.episodes)
    else:
        train(
            num_episodes=args.episodes,
            use_trl_trainer=not args.no_trl,
            use_model=True,
            verbose=not args.quiet,
        )
